### ISSUE TITLE
Error in Backend and Command to run project 

### ISSUE THREAD

**Issue by kalyan1421** [zakaria-narjis/Diet-Recommendation-System#2]
Useing command  python -m streamlit run Hello.py in Streamlit_Forntend
Error in backend at
ConnectionError: HTTPConnectionPool(host='backend', port=8080): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022E63DFA320>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
 please let me know how to start project and run the project 
my email:kalyan91333@gmail.com

**Comment by zakaria-narjis** [comment]
I assume you are not using docker compose. Therefore, you should change the endpoint here [Diet-Recommendation-System](https://github.com/zakaria-narjis/Diet-Recommendation-System)/[Streamlit_Frontend](https://github.com/zakaria-narjis/Diet-Recommendation-System/tree/main/Streamlit_Frontend)/Generate_Recommendations.py. You should put http://your_ip:8080/predict/. You should however run the backend beforehand. Run the backend with uvicorn main:app --host 0.0.0.0 --port 8080 --reload. Then, you can run the front end as you did with python -m streamlit run Hello.py. Just make sure you have the correct endpoint in the Generate_Recommendations.py file.

**Comment by siddhuvinayak** [comment]
hi bro there is a problem while using this code i.e; server is not connecting so please rectify my problem
my email is karthikeyasolasa@gmail.com
![WhatsApp Image 2023-12-26 at 3 27 51 PM](https://github.com/zakaria-narjis/Diet-Recommendation-System/assets/123713743/06961574-6c92-4e08-8eb8-7a444e1d7475)

**Comment by kalyan1421** [comment]
Yes bro ,
But I am busy in different projects
If you need mobile app diet I can provide with some charges

**Comment by siddhuvinayak** [comment]
Only  we want diet  recommendations system
How much

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kalyan1421** [comment]
I will message you back

**Comment by siddhuvinayak** [comment]
Ok

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by prasannakotyal** [comment]
Hello, I tried running using docker compose and the yml file ran completely and this is the messagge i got in my vs code terminal                                                                                                         0.0s 
[+] Running 2/3
 - Network diet-recommendation-system-main_project_network  Created                                                                                             1.1s 
 ✔ Container diet-recommendation-system-main-backend-1      Started                                                                                             0.6s 
 ✔ Container diet-recommendation-system-main-frontend-1     Started                                                                                             0.9s 
PS C:\Users\Prasanna Kotyal\Downloads\Diet-Recommendation-System-main\Diet-Recommendation-System-main> 
after this when i checked my docker desktop it did not have a port open for frontend. please help me resolve this.
I have attached the image for your reference[
![Screenshot (10)](https://github.com/zakaria-narjis/Diet-Recommendation-System/assets/66207940/67f011ca-4130-4cb2-8d07-2451b42a5f14)
]
